<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Surveys') ?></h1>
    </div>
    <?php $dataCol = $this->getSurveyOfCustomer(); ?>
    <?php if ( count($dataCol)!= 0 ) : ?>
        <table>
            <tr>
                <th><?php echo $this->__('Question'); ?></th>
                <th><?php echo $this->__('Answer'); ?></th>
                <th><?php echo $this->__('Answered When'); ?></th>
            </tr>
        <?php   foreach($dataCol as $data) : ?>
            <tr>
                <td><?php echo $data['question_title'] ?></td>
                <td><?php echo $data['question_answers'] ?></td>
                <td><?php echo $data['created_at'] ?></td>
            </tr>
        <?php   endforeach; ?>
        </table>
    <?php  else : ?>
            <p><?php echo $this->__('You have not yet answered any survey!'); ?></p>
    <?php endif; ?>
</div>